<a href="https://colab.research.google.com/github/Akshaya1409/Python-Libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Numpy in Python 

importing numpy library

In [3]:
import numpy as np

Numpy one dimensional array
       
          Numpy arrays can be created from list 

In [4]:
country=["India","China","Canada","America"]      # country is a list containing 4 elements
coun_array=np.array(country)    # using np.array  the list is being converted to an 1-D array 
print(coun_array,type(coun_array))    

['India' 'China' 'Canada' 'America'] <class 'numpy.ndarray'>


In [5]:
country=[121,"hi"]          
aray=np.array(country)
aray                                    

array(['121', 'hi'], dtype='<U21')

**Generating random arrays**

In [6]:
np.random.random(size=15)          # random.random()  shows the number ranging from 0 to 1

array([0.81163227, 0.78242123, 0.10342253, 0.24977719, 0.87340753,
       0.1508518 , 0.30700127, 0.38604365, 0.64514704, 0.31634832,
       0.80568357, 0.76879473, 0.93215167, 0.5118448 , 0.33613964])

In [7]:
np.random.rand(3,3)   # generates random numbers from 0 to 1 in the 3x3 format

array([[0.37876089, 0.17911745, 0.59847202],
       [0.12594216, 0.9953254 , 0.58820839],
       [0.15482041, 0.47322215, 0.01452242]])

In [8]:
np.random.randn(3,3)  

array([[-0.95347854, -0.80082704, -0.74845124],
       [ 0.27727863,  1.71897465, -1.31744603],
       [ 0.64970514,  0.78102757,  0.6964143 ]])

In [9]:
print(np.arange(10,20,5))          # generates the numpy array with the given range 10 to 20(exclusive) with step count of 5

[10 15]


In [10]:
print(np.linspace(0,5,10))   # generates specified number of values in the given range

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [11]:
matrix=np.empty((3,3),dtype=int)      # generates a 2d array
matrix                            

array([[4603179219131243634, 4607682818758614130, 4610184818551597739],
       [4612186418385984626, 4613437418282476430, 4614688418178968235],
       [4615939418075460040, 4616690018013355122, 4617315517961601024]])

In [12]:
np.identity(4)           # creates an 4x4  identity matrix 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

np.eye() creates a 2x2 matrix with value as 1 in the kth diagonal and zeros as remaining entries

In [13]:
np.eye(4,4,1)    # here k>1 so the upper diagonal is filled with 1 and rest as zeros

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [14]:
np.eye(4,4,-2)    # here k<1 so the lower diagonal is filled with 1 and rest as zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

##Array Attributes

In [15]:
#shape returns the no.of rows and columns of an array 
country=np.array([("India",'China',"Canada","America"),(1,2,3,25)])

print(country.shape)                                

(2, 4)


In [16]:
country.size  # returns no of elements

8

In [17]:
country.dtype

dtype('<U7')

**Array Indexing and slicing**


  **In 1D array**

In [18]:
country[1:]   # prints 1st row 

array([['1', '2', '3', '25']], dtype='<U7')

In [19]:
country[1:,:1]    # first row, first element is printed

array([['1']], dtype='<U7')

In [27]:
country[1:,:-1]  

array([['1', '2', '3']], dtype='<U7')

**Slicing in 2D Array**

 **In 2D array**

In [21]:
mat=np.array([(12,25,36),(45,3,98)])
print(mat[1:,:1])                      # prints 1st row 1st column  element with index=0 

[[45]]


In [22]:
print(mat[0:,:2])  

[[12 25]
 [45  3]]


**Numpy: Array addition and subtraction**

In [23]:
ar=np.array(np.random.randint(1,5,5))        # randomly generated  equisized 2 array 
a=np.array(np.random.randint(1,10,5)) 
print(ar+a)  # adding those array
print(ar-a)  # subtracting them     
print(ar*2)   # multiplying them

[5 3 6 4 9]
[-3 -1  2  0 -7]
[2 2 8 4 2]


In [24]:
A=np.array(np.random.randint(1,10,5))
print(A)
print(A.min())      # minimum in the list
print(A.argmin())       # minimum's position  in the list
print(A.max())             # maximum in the list
print(A.argmax()) # maximum's position in the list

[4 2 5 3 4]
2
1
5
2


Elemet wise multiplication 

In [25]:
mul=np.array([(1,2,3),(4,5,6)])
m=np.array([(11,0,1),(1,5,7)])
print(mul*m)                         

[[11  0  3]
 [ 4 25 42]]


In [28]:
matrix_mul=mul.dot(m)                # In order to do matrix  multiplication the no.of rows in first matrix must be equal to no.of columns in the 2nd one

ValueError: ignored

In [29]:
a=np.array([(1,2,3),(4,5,6)])      
b=np.array([(11,1),(1,7),(4,5)])               # Matrix multiplication by dot() operation 
mat_mul=a.dot(b)
print(mat_mul)                 # 2x3.dot(3x2) = 2x2 matrix 

[[25 30]
 [73 69]]


In [30]:
np.transpose(mat_mul)        # transposing the rows to columns and columns to rows

array([[25, 73],
       [30, 69]])

### Concatenating two 1D Array

In [34]:
x=np.array([1,2,3])       
y=np.array([5,6,9])
print("Array 1D-->",x)
print("Array 1D-->",y)
print("The concatenated array -->",np.concatenate([x,y]))

Array 1D--> [1 2 3]
Array 1D--> [5 6 9]
The concatenated array --> [1 2 3 5 6 9]


### Concatenating 2D Array

In [36]:
a=np.array([(1,2),(4,5)])      
b=np.array([(11,1),(1,7),(4,5)])  
print("Concatenated 2D Array",np.concatenate([a,b])) 

Concatenated 2D Array [[ 1  2]
 [ 4  5]
 [11  1]
 [ 1  7]
 [ 4  5]]


In [37]:
a=np.array([(1,2),(4,5),(9,9)])      
b=np.array([(11,1),(1,7),(4,5)])  
print(np.concatenate([a,b]))            

[[ 1  2]
 [ 4  5]
 [ 9  9]
 [11  1]
 [ 1  7]
 [ 4  5]]


###Assignment

 1. Creating a null vector 

In [ ]:
arr=np.zeros(10)


 2. Create a null vector with size 10 and assign 5th values as 1

In [ ]:
nullvec=np.zeros(10)
nullvec[4] = 1
nullvec

3.generate 10 random numbers from 20-35

In [ ]:
 arr=np.array(np.random.randint(20,35,10))
 arr

4. reverse the generated random number

In [ ]:
arr[::-1]